JunctionX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

...


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls')),
    path('', include('userhandler_app.urls')),
    path('', include('children_app.urls')),
    path('', include('qrcode_app.urls')),
    path('', include('tale_app.urls')),
    path('', include('statistics_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = 'basic_app'

urlpatterns = [
    # HOMEPAGE
    path('index/', views.index, name="index"),
    path('login/', views.login, name="login"),
]

children_app/urls.py
from django.urls import path

from children_app import views

app_name = 'children_app'

urlpatterns = [
    # HOMEPAGE
    path('', views.ChildList.as_view(), name="child"),
    path('child/add', views.AddChild.as_view(), name="add_child"),
    path('child_<int:child_id>/settings', views.SettingChild.as_view(), name="setting_child"),
]

tale_app/urls.py
from django.urls import path
from tale_app import views

app_name = 'tale_app'

urlpatterns = [
    path('child_<int:child_id>/tales', views.TalesList.as_view(), name="TalesList"),
    path('child_<int:child_id>/tales_<int:tale_id>/start', views.TaleStart.as_view(), name="TaleStart"),
    path('child_<int:child_id>/tales_<int:tale_id>/end', views.TaleEnd.as_view(), name="TaleEnd"),
    path('child_<int:child_id>/tales_<int:tale_id>/content_<int:content_id>', views.TaleContent.as_view(), name="TaleContent"),
    path('child_<int:child_id>/tales_<int:tale_id>/content_<int:content_id>/upload', views.TaleUpload.as_view(),
         name="TaleUpload"),
]

userhandler_app/urls.py
from django.urls import path
from . import views

app_name = 'userhandler_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('accounts/login/', views.user_login, name='user_login'),
    path('accounts/logout/', views.user_logout, name='logout'),

]

basic_app/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin


# ============================================================================================
# Index page.
# ============================================================================================
def index(request):
    return render(request, 'basic_app/index.html')


def login(request):
    return render(request, 'userhandler_app/login.html')

templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>

  <meta charset="utf-8">
  <title>E-Aid</title>
  <script src="{% static 'jQuery/jquery-3.4.1.js' %}"></script>
  <script src="{% static 'jQuery/jquery-ui.js' %}"></script>
  <script src="{% static 'jQuery/popper.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'Bootstrap/css/bootstrap.css' %}">
  <script src="{% static 'Bootstrap/js/bootstrap.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'DataTables/jquery.dataTables.min.css' %}" />
  <script src="{% static 'DataTables/jquery.dataTables.min.js' %}"></script>
  <link href="{% static "icons/css/all.css" %}" rel="stylesheet">
  <script defer src="{% static 'icons/js/all.js' %}"></script>
  <link rel="stylesheet" href="{% static "css/override.css" %}">

  <link rel="shortcut icon" type="image/png" href="{% static 'basic_app/pictures/logomini.png' %}" />


</head>

<body>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container">
      <div class="navbar-nav float-none">
        <a class="navbar-brand float-none" href="{% url 'children_app:child' %}">

          <img src="{% static "basic_app/pictures/microsoft.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <img src="{% static "basic_app/pictures/logomini.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">

          Home
        </a>

<!--        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>-->
          <a class="nav-item nav-link" href="{% url 'children_app:child' %}">Children</a>
      </div>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"> Hello, {{user.username}}!</span>
            <a class="btn btn-dark" href="{% url 'userhandler_app:logout' %}" role="button">Logout</a>
          </li>

          {% else %}
          <li class="nav-item">
              <a class="btn btn-dark" href="{% url 'userhandler_app:register' %}" role="button">Register</a>
          </li>
<!--          <li class="nav-item">-->
<!--              <a class="btn btn-dark ml-1" href="{% url 'userhandler_app:user_login' %}?next={{request.path}}" role="button">Login</a>-->
<!--          </li>-->
          {% endif %}
        </ul>
      </div>



  </nav>

  <div class="container">
    <!-- {{ nav |safe }} -->
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
  </div>
  <div class="container">
    {% block button_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
  </div>

</body>


</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block%}
{% load static%}
<div class="jumbotron mt-4">
    <div class="text-center">
    <img src="{% static "basic_app/pictures/logo.png"%}" width="600" height="300" alt="">
    </div>
    <br>
    <div style="text-align: Left;">
        <h1 class="display-4">Welcome  </h1>
        <a  style="margin:auto" class="btn btn-primary btn-lg" href="{% url 'userhandler_app:logout' %}" role="button">Children</a>
    </div>
</div>



{% endblock %}

templates/basic_app/talebase.html
<!DOCTYPE html>
{% load static %}
<html>

<head>

  <meta charset="utf-8">
  <title>Tales</title>
  <script src="{% static 'jQuery/jquery-3.4.1.js' %}"></script>
  <script src="{% static 'jQuery/jquery-ui.js' %}"></script>
  <script src="{% static 'jQuery/popper.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'Bootstrap/css/bootstrap.css' %}">
  <script src="{% static 'Bootstrap/js/bootstrap.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'DataTables/jquery.dataTables.min.css' %}" />
  <script src="{% static 'DataTables/jquery.dataTables.min.js' %}"></script>
  <link href="{% static "icons/css/all.css" %}" rel="stylesheet">
  <script defer src="{% static 'icons/js/all.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/override.css' %}">

  <link rel="shortcut icon" type="image/png" href="{% static 'basic_app/pictures/logomini.png' %}" />


</head>

<body>


  <div class="container">
    <!-- {{ nav |safe }} -->
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
  </div>
  <div class="container">
    {% block button_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
  </div>

</body>

<style>
body {
    background-repeat: no-repeat;
    background-size: auto;
    background-position-x: center;
    background-color: #ffe68b;
}
</style>


</html>