JunctionX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

...


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls')),
    path('', include('userhandler_app.urls')),
    path('', include('children_app.urls')),
    path('', include('qrcode_app.urls')),
    path('', include('tale_app.urls')),
    path('', include('statistics_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

children_app/urls.py
from django.urls import path

from children_app import views

app_name = 'children_app'

urlpatterns = [
    # HOMEPAGE
    path('', views.ChildList.as_view(), name="child"),
    path('child/add', views.AddChild.as_view(), name="add_child"),
    path('child_<int:child_id>/settings', views.SettingChild.as_view(), name="setting_child"),
]

tale_app/urls.py
from django.urls import path
from tale_app import views

app_name = 'tale_app'

urlpatterns = [
    path('child_<int:child_id>/tales', views.TalesList.as_view(), name="TalesList"),
    path('child_<int:child_id>/tales_<int:tale_id>/start', views.TaleStart.as_view(), name="TaleStart"),
    path('child_<int:child_id>/tales_<int:tale_id>/end', views.TaleEnd.as_view(), name="TaleEnd"),
    path('child_<int:child_id>/tales_<int:tale_id>/content_<int:content_id>', views.TaleContent.as_view(), name="TaleContent"),
    path('child_<int:child_id>/tales_<int:tale_id>/content_<int:content_id>/upload', views.TaleUpload.as_view(),
         name="TaleUpload"),
]

userhandler_app/urls.py
from django.urls import path
from . import views

app_name = 'userhandler_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('accounts/login/', views.user_login, name='user_login'),
    path('accounts/logout/', views.user_logout, name='logout'),

]

children_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Child(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    name = models.CharField(db_column='Name', max_length=128, blank=True, null=True)
    image = models.ImageField(db_column='image', upload_to='children_app/pictures', blank=True)
    user = models.ForeignKey(User, models.CASCADE, db_column='userID')
    wholescore = models.IntegerField(blank=True, default=0)
    sessionscore = models.IntegerField(blank=True, default=0)
    emojitype = models.IntegerField(blank=True, default=1)


    class Meta:
        db_table = 'child'

    def __str__(self):
        return 'ID:{} Name:{}'.format(self.id, self.name)

children_app/forms.py
from django import forms
from .models import Child


class AddChild(forms.ModelForm):

    class Meta:
        model = Child
        fields = ('name', 'image')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}),

        }
        labels = {
                'name': "Name of the family member:",
        }

    def clean(self):
        all_clean_data = super().clean()


class SettingsEmoji(forms.ModelForm):

    class Meta:
        model = Child
        fields = ('emojitype',)
        widgets = {
            'emojitype': forms.NumberInput(attrs={'min': '1', 'max': '2'}),

        }
        labels = {
                'emojitype': "Type of the emoji: ",
        }

    def clean(self):
        all_clean_data = super().clean()

children_app/views.py
from django.shortcuts import render
from .models import Child
from . import forms
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect


class ChildList(LoginRequiredMixin, TemplateView):
    template_name = "children_app/list.html"

    def get_context_data(self, **kwargs):  # Ez a két sor itt ahhoz kell, hogy hozzáférjük a context-hez
        # amit belerakunka template-be
        context = super().get_context_data(**kwargs)
        all_child = Child.objects.filter(
            user=User.objects.get(pk=self.request.user.id)
        ).order_by('name')
        context['items'] = all_child
        return context


class AddChild(LoginRequiredMixin, TemplateView):
    template_name = 'children_app/add.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.AddChild()
        return context

    def post(self, request, *args, **kwargs):

        form = forms.AddChild(request.POST, request.FILES)
        if form.is_valid():  # HA rendben van a form tartalma
            print("VALID FORM IN.")

            r1 = Child(
                    name=form.cleaned_data['name'],
                    image=form.cleaned_data['image'],
                    user=User.objects.get(pk=self.request.user.id),
                )
            r1.save()  # az osztály példányának mentésével írom az adatbázisba az adatokat
            return HttpResponseRedirect(reverse('children_app:child'))
        else:
            return render(request, 'children_app/add.html', {'form': form})


class SettingChild(LoginRequiredMixin, TemplateView):
    template_name = "children_app/setting.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        child = Child.objects.get(pk=kwargs['child_id'])
        settingform = forms.SettingsEmoji(instance=child)
        context['form'] = settingform
        return context

    def post(self, request, *args, **kwargs):
        form = forms.SettingsEmoji(request.POST, request.FILES)
        if form.is_valid():
            print("VALID FORM IN.")
            child = Child.objects.get(pk=kwargs['child_id'])
            child.emojitype = form.cleaned_data['emojitype']
            child.save()

            return HttpResponseRedirect(reverse('children_app:child'))

templates/children_app/add.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block%}


<div class="mt-3">
    <h1>Add Family Member</h1>
</div>
<form enctype="multipart/form-data"  method="post"  class= "add_form" >
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" name="" value="Submit">
</form>
{% endblock %}

templates/children_app/list.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}



{% block body_block%}
{% if user.is_authenticated %}
{%load static%}
<div class="mt-3">
  <h1>Your group members:</h1>
</div>


{% if items %}
<ul>
  <div id="sortable" class="row">
    {% for item in items %}
    <div class="col-md-6 col-xl-4 mt-3 mb-3 cardholder">
      <div class="card">
        <div class="card-body bg-light text-center">

            <img src="{{ item.image.url }}" alt="img" style="max-width:100%;max-height:100%;">
            <div class="text-center">
                <h5 class="card-title mt-3">{{ item.name}}</h5>
            </div>

          <div class="text-center">
            <button data-id="{{item.id}}" type="button" class="btn btn-secondary select_child_button" >
              <div>
                <i style="width: 35px; height: 35px;" class="fas fa-chart-bar"></i>
              </div>
              <div>
                <span>Statistics </span>
              </div>


            </button>
            <button data-id="{{item.id}}" type="button" class="btn btn-secondary generate_qr_button" >
              <div>
                <i style="width: 35px; height: 35px;" class="fas fa-qrcode"></i>
              </div>
              <div>
                <span style="">QR</span>
              </div>
            </button>
              <button data-id="{{item.id}}" type="button" class="btn btn-secondary child_settings_button" >
              <div>
                <i style="width: 35px; height: 35px;" class="fas fa-cog"></i>
              </div>
              <div>
                <span style="">Settings</span>
              </div>
            </button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</ul>
{% endif %}
<a href="{% url 'children_app:add_child' %}" class="btn btn-success">  <i  class="fas fa-plus"></i> Add child</a>
{% csrf_token %}

<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src = "{% static 'js/navigation.js' %}"></script>


{% else %}


{% load static%}
<style>
  .smallbox {width:250px;  float: right;  overflow: auto;}
  .clearfix {
    overflow: auto;

  }
  .right{float: right;}
  .left{float: left;}
  .rounded5{border-radius: 5px;}
</style>


<div class="jumbotron clearfix mt-4">
  <div>
    <h1>Welcome To Emotional Aid!</h1>
    <p class="lead">We provide help for children who find it difficult to express or recognize emotions and much-much more! </p>
  </div>
  <div class="left">
    <img src="{% static 'pictures/children.jpg'%}" width="700" height="400" class="rounded5" alt="">

  </div>

  <div class="smallbox mr-5">
    <h1 class="mb-2">Sign In</h1>
    <form action="{% url 'userhandler_app:user_login' %}" method="POST">
      {% csrf_token %}
      <div class="form-group mt-3" >
        <label for="username">Username: </label>
        <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username">

        <label for="password">Password: </label>
        <input type="password" class="form-control" id="password" name="password">
        <input type="hidden" name="next" value="{{ request.GET.next}}"/>

        <input name="" class = "mt-3 btn btn-primary" type="submit" value="Sign In!">
      </div>
    </form>
  </div>
</div>
{% endif %}
{% endblock %}

templates/children_app/setting.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block%}


<div class="mt-3">
    <h1>Modify settings</h1>
</div>
<form method="post"  class= "add_form" >
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" name="" value="Submit">
</form>
{% endblock %}